# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c999101a0af90dca82b01f13b5eb94fdeaf49468f7836125771ba7569bcb5ff7b6b56cb474ca8dba39e08cdea13b2f4d7b001fc3bc012f57a871915bb349060

test:
  secret_key_base: bb40392e96e729c22d98737687d664f0710de3905ce583b7841e230146ce3ccfc97bc9f42ca4552c8fc847530c55ed3484431ce9e6ecf520c2303961d9cff42e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
